"""Added image_path and description to Artwork

Revision ID: 781748349095
Revises: ebdd8601e808
Create Date: 2025-02-03 16:03:27.019714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781748349095'
down_revision = 'ebdd8601e808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
